# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{.Chart.Name}}-{{ .Chart.Version }}
    component: {{ .Chart.Name }}
    release: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
