# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: discovery-operator-metrics-monitor
  # the service monitor has to be in the OCP Prometheus namespace
  namespace: openshift-monitoring
spec:
  endpoints:
  - path: /metrics
    interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
